name: Tag on Merge to Staging

on:
  push:
    branches:
      - staging

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: new_version
        run: |
          latest="${{ steps.get_latest_tag.outputs.latest }}"
          stripped=${latest#v}
          IFS='.' read -r major minor patch <<< "$stripped"
          new_tag="v$major.$minor.$((patch + 1))"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.new_version.outputs.new_tag }}
          git push origin ${{ steps.new_version.outputs.new_tag }}
