# .github/workflows/tag-rc-on-staging.yml
name: Tag RC on Staging Push

on:
  push:
    branches:
      - staging

jobs:
  tag_rc:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest main version
        id: get_main_version
        run: |
          # Get the latest full release tag (no -rc suffix)
          latest_main=$(git tag --list 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "Latest main version: $latest_main"
          echo "main_version=$latest_main" >> $GITHUB_OUTPUT

      - name: Get latest RC for this version
        id: get_latest_rc
        run: |
          main_version="${{ steps.get_main_version.outputs.main_version }}"
          # Extract the highest RC number for that version
          latest_rc=$(git tag --list "${main_version}-rc.*" | sort -V | tail -n 1)
          
          if [[ -z "$latest_rc" ]]; then
            new_tag="${main_version}-rc.1"
          else
            rc_num=$(echo "$latest_rc" | grep -o 'rc\.[0-9]*' | cut -d'.' -f2)
            new_rc_num=$((rc_num + 1))
            new_tag="${main_version}-rc.${new_rc_num}"
          fi

          echo "Creating new RC tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.get_latest_rc.outputs.new_tag }}
          git push origin ${{ steps.get_latest_rc.outputs.new_tag }}
