# .github/workflows/tag-on-staging.yml
name: Tag and Release on Staging

on:
  push:
    branches:
      - staging

jobs:
  tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest RC tag
        id: get_latest_tag
        run: |
          # Get latest RC tag for the format vX.Y.Z-rc.N
          latest_tag=$(git tag --list 'v*-rc.*' --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump RC tag
        id: bump_tag
        run: |
          latest_tag="${{ steps.get_latest_tag.outputs.latest_tag }}"

          if [[ -z "$latest_tag" ]]; then
            new_tag="v1.0.0-rc.1"
          else
            version=$(echo "$latest_tag" | cut -d'-' -f1)
            rc_num=$(echo "$latest_tag" | grep -o 'rc\.[0-9]*' | cut -d'.' -f2)
            new_rc_num=$((rc_num + 1))
            new_tag="${version}-rc.${new_rc_num}"
          fi

          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump_tag.outputs.new_tag }}
          git push origin ${{ steps.bump_tag.outputs.new_tag }}
